### ISSUE TITLE
seedPrivate and privateToPublic

### ISSUE THREAD

**Issue by shamtroon** [EOSIO/eosio-swift-ecc#63]
Hi guys, I want to integrate eosio-swift-ecc for creating pubic and private key-pair from a seed. In **eosio-ecc** of **JavaScript** there is a functionality of **seedPrivate** and  **privateToPublic**, but I didn't see any functionality like this, in **eosio-swift**.

**Comment by jafri** [comment]
@shamtroon privateToPublic is recoverPublicKey

**Comment by shamtroon** [comment]
@jafri and what about **seedPrivate**, by which we can generate a new public-private key pair.

**Comment by jke661s** [comment]
I see eosio js and eosio java have this seedPrivate and I'm also looking for it in swift sdk. Just wondering whether it exists in the current sdk?

**Comment by opi-smccoole** [comment]
Sorry, generating a deterministic private key is inherently insecure so that is not supported in the swift libraries.  Key generation should always be done using the keychain/secure enclave functionality from eosio-swift-vault.  You can import keys generated in alternate ways but it is assumed that you have generated them by some other means.

**Comment by opi-smccoole** [comment]
If you still really want to do it, even though it is not a good idea, you could do something like this to essentially match what eosjs does:
```
let data = seedString.data(using: .utf8)
let hash = data.sha256
let privateKeyString = String(hash.toEosioK1PrivateKey.dropFirst(7))
```
Then use `recoverPublicKey` to get that.

**Comment by opi-smccoole** [comment]
Also note that the functionality here is now folded into eosio-swift in the latest release and the standalone eosio-swift-ecc package is now deprecated.

**Comment by jke661s** [comment]
@opi-smccoole That works! It saves my life. Thank you.
