### ISSUE TITLE
Signature is not deterministic?

### ISSUE THREAD

**Issue by anqishao** [EOSIO/eosio-swift-ecc#75]
Hi, when I use signWithK1 function to sign the same hash value with same private key, the signatures I get are different each time. And none of them is the same as I get from other language(like eos-go). When I check the code in eos-go, it seems use compact signature there which make sure the signature is deterministic. How can I get the same result in this library. Thank you very much.

**Comment by wjd-jax** [comment]
I encountered the same problem, and the signature was not verified in Dapp

**Comment by opi-smccoole** [comment]
To do this you would have to provide a signature method that removed the random generator input to the message signing.  The library currently does not support this.  If you look at the current implementation, you could modify it to do this, but it is not recommended.
