### ISSUE TITLE
KeySigningError: Unable to find recid for...

### ISSUE THREAD

**Issue by Mattijah** [EOSIO/eosio-swift-ecc#76]
It seems like the same fix as done here https://github.com/EOSIO/eosio-swift-ecc/commit/3d050c5d2098361a98d8a2e34478b5d2e72a477c by @opi-smccoole must also be implemented for the 2nd variation: `EccRecoverKey:recoverPublicKey(signatureDer, message, recid, curve)` which is used in the `EccRecoverKey:recid` to compare the keys.

**Comment by opi-smccoole** [comment]
This is fixed in the v0.3.0 release.
